### ISSUE TITLE
Zoomie Button No Longer Available.

### ISSUE THREAD

**Issue by BigDanHouston** [davidshumway/zoomie#3]
I was trying to create some zoomie round-robin breakout rooms as I did in some previous meetings, but the zoomie button is suddenly unavailable. Not sure if this is something to do with zoom, but it would be great to take advantage of your software again.

**Comment by davidshumway** [comment]
Fixed. Issue was site layout changes by Zoom. New version has been approved on Firefox add-ons and is live now.
